// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import RoleSelectorController from "./role_selector_controller"
application.register("role-selector", RoleSelectorController)
