// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CommunityEditController from "./community_edit_controller";
application.register("community-edit", CommunityEditController);

import NotificationsController from "./notifications_controller";
application.register("notifications", NotificationsController);

import RoleSelectorController from "./role_selector_controller";
application.register("role-selector", RoleSelectorController);

import ServerEditController from "./server_edit_controller";
application.register("server-edit", ServerEditController);

import ServerModsController from "./server_mods_controller";
application.register("server-mods", ServerModsController);

import ServerNewController from "./server_new_controller";
application.register("server-new", ServerNewController);
